#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm lint-staged
pnpm exec tsc --noEmit
CHANGED_FILES=$(git diff --cached --name-only --relative | tr '\n' ' ')
if [ -n "$CHANGED_FILES" ]; then
  pnpm exec vitest related --run --passWithNoTests $CHANGED_FILES
fi
