name: Nightly Load & Chaos

on:
  schedule:
    - cron: "10 2 * * *"
  workflow_dispatch: {}

jobs:
  k6-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run k6 smoke
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load/k6/smoke.js
        env:
          BASE_URL: ${{ secrets.K6_BASE_URL }}
          BEARER:   ${{ secrets.K6_BEARER }}
          CONV_ID:  ${{ secrets.K6_CONV_ID }}
          SENDER_ID: ${{ secrets.K6_SENDER_ID }}

  k6-burst:
    runs-on: ubuntu-latest
    needs: k6-smoke
    steps:
      - uses: actions/checkout@v4
      - name: Run k6 burst
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load/k6/burst.js
        env:
          BASE_URL: ${{ secrets.K6_BASE_URL }}
          BEARER:   ${{ secrets.K6_BEARER }}
          CONV_ID:  ${{ secrets.K6_CONV_ID }}
          SENDER_ID: ${{ secrets.K6_SENDER_ID }}

  # Optional weekly soak; keep disabled by default
  # k6-soak:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'schedule'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run k6 soak
  #       uses: grafana/k6-action@v0.3.1
  #       with:
  #         filename: load/k6/soak.js
  #       env:
  #         BASE_URL: ${{ secrets.K6_BASE_URL }}
  #         BEARER:   ${{ secrets.K6_BEARER }}
  #         CONV_ID:  ${{ secrets.K6_CONV_ID }}
  #         SENDER_ID: ${{ secrets.K6_SENDER_ID }}

name: Load and Chaos Tests

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  load_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
      - run: pnpm install
      - name: Run k6 load test
        run: |
          npm install -g k6
          k6 run packages/storage/tests/load/k6/stream_load_test.js
        env:
          STREAM_URL: ${{ secrets.STREAM_URL }}
          STREAM_TOKEN: ${{ secrets.STREAM_TOKEN }}

  chaos_tests:
    runs-on: ubuntu-latest
    needs: load_tests
    services:
      toxiproxy:
        image: shopify/toxiproxy
        ports:
          - 8474:8474
          - 16379:16379
          - 19001:19001
    steps:
      - uses: actions/checkout@v4
      - run: pnpm install
      - name: Configure toxiproxy
        run: |
          curl -s http://localhost:8474/populate -XPOST --data-binary @packages/storage/tests/chaos/toxiproxy.config.json
      - name: Inject Redis latency
        run: packages/storage/tests/chaos/scripts/redis_latency.sh
      - name: Inject S3 disconnect
        run: packages/storage/tests/chaos/scripts/s3_disconnect.sh


